### ISSUE TITLE
[Tracker] Known Issues 

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2477]
Tracker Ticket to easily reference current known issues. These are major playback, stability or otherwise known issues. They are ordered mostly by severity. 

- [ ] https://github.com/jellyfin/jellyfin/issues/2547 / https://github.com/jellyfin/jellyfin-web/issues/879 / https://github.com/jellyfin/jellyfin-android/issues/301 / https://github.com/jellyfin/jellyfin-expo/issues/54 Audio/Video playback position wrong after changing playback position due to non-keyframe HLS use
- [ ] https://github.com/jellyfin/jellyfin-androidtv/issues/308 AndroidTV Unable to Fast Forward
- [ ] https://github.com/jellyfin/jellyfin-androidtv/issues/400 Media goes back to beginning while playing
- [ ] https://github.com/jellyfin/jellyfin-androidtv/issues/292 AndroidTV HEVC 10-bit transcodes while Exoplayer supports it
- [ ] https://github.com/jellyfin/jellyfin/issues/2691 Libraries with subdirectories 3+ aren't scanned properly 
- [ ] https://github.com/jellyfin/jellyfin/issues/2600 Very slow initial Library scan
- [ ] https://github.com/jellyfin/jellyfin/issues/2441 Regex Issues
- [ ] https://github.com/jellyfin/jellyfin/issues/2355 / https://github.com/jellyfin/jellyfin/issues/2471 Screen Grabber/Image Extractor is partially broken. (I suspect only docker)
- [ ] https://github.com/jellyfin/jellyfin/issues/1269 [JF >= 10.3] thumbnail extraction now pegs CPU at 100%
- [ ] https://github.com/jellyfin/jellyfin/issues/2239 External VOBSUB are treated as SRT
- [ ] https://github.com/jellyfin/jellyfin-androidtv/issues/414 AndroidTV will transcode unnecessarily 
- [ ] https://github.com/jellyfin/jellyfin-web/issues/1077 Embedded MKV S_TEXT/UTF8 subtitles don't render correctly
- [ ] https://github.com/jellyfin/jellyfin/issues/1623 Plugin Update/Uninstall is failing on Windows
- [ ] https://github.com/jellyfin/jellyfin/issues/2125 Setting an Empty PIN is bugged
- [ ] https://github.com/jellyfin/jellyfin/issues/2424 Profiles aren't dynamic enough and cause some stray devices to not have proper playback
- [ ] https://github.com/jellyfin/jellyfin/issues/2281 Docker arm has permission issues for HWA
---
- [x] https://github.com/jellyfin/jellyfin/issues/2402 Library scanning is aborted if doesn't have permission in any of subfolders
- [x] https://github.com/jellyfin/jellyfin/issues/3239 TV shows and Albums displayed in 'Latest Media' is limited 
- [x] https://github.com/jellyfin/jellyfin-web/issues/1085 Page reload during playback yields error
- [x] https://github.com/jellyfin/jellyfin/issues/2377 BaseURL breaks DLNA (and probably more)
- [x] https://github.com/jellyfin/jellyfin/issues/2760 Websocket leakage causing excessive RAM usage. 
- [x] https://github.com/jellyfin/jellyfin-server-windows/issues/18#issuecomment-562814135 Windows tray app breaks
- [x] https://github.com/jellyfin/jellyfin/issues/2273 Remuxing causes issues with Anamorphic Videos.
- [x] https://github.com/jellyfin/jellyfin/issues/2654 LDAP is broken.
- [x] https://github.com/jellyfin/jellyfin/issues/2747 500 File Limit per Folder
- [x] https://github.com/jellyfin/jellyfin/issues/2259 Secure Connections Mode Issues
- [x] https://github.com/jellyfin/jellyfin/issues/2565 Collections Metadata lost after update to 10.5
- [x] https://github.com/jellyfin/jellyfin/issues/3064 Collections don't work as expected
- [x]  https://github.com/jellyfin/jellyfin/issues/2881 Incorrect etags in /Users/{UserId}/Items when using the Recursive flag
- [x] https://github.com/jellyfin/jellyfin/issues/2484 Extras don't work
- [x] https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/6 Collections plugin broken and *crashes the server* 
- [x] https://github.com/jellyfin/jellyfin-web/issues/833 Admins can't edit user profiles
- [x] https://github.com/jellyfin/jellyfin-web/issues/899 Resume not working on Chrome Mobile/Android
- [x] https://github.com/jellyfin/jellyfin-android/issues/254 Music Transcoding is broken on Android
- [x] https://github.com/jellyfin/jellyfin-android/issues/228 HEVC Playback is broken on Android
- [x] https://github.com/jellyfin/jellyfin/issues/2525 external Srt subs without BOM encoding don't work 
- [x] https://github.com/jellyfin/jellyfin/issues/2435 PGS Subtiles currently don't display unless Burned-In

**Comment by rscm** [comment]
#2525 still happening on Jellyfin 10.5.5

had to run the command on the media library root directory as a bypass
