### ISSUE TITLE
Release version 10.0.0

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin#253]
Let's start jellyfin's version over with a 10.0.0 release. Then we can more away from the inappropriate dash versioning we have currently.

- [ ] Ensure version in API responses corresponds to the Emby API it implements.
- [ ] Rebrand https://github.com/jellyfin/jellyfin/issues/25
- [ ] Logo https://github.com/jellyfin/jellyfin/issues/101

**Comment by LeoVerto** [comment]
IMHO jumping straight to 10.0.0 is somewhat of a confusing move. I think that instead going to 4.0.0 would be a lot clearer and still give us a large enough buffer in regards to Emby's versioning (so as to not confuse users).

By the time (and if) they do "catch up" we've hopefully diverged far enough to be seen as more than just a fork and rather an entirely alternative piece of software.

**Comment by joshuaboniface** [comment]
I agree with @nvllsvm on just doing a clean version break. @JustAMan suggested going down to 0.X but I'd rather us go. Airsonic jumped from 6.X to 10 when they completed their forking, and I think following that model as @nvllsvm suggests is a good idea.

Any version change would be confusing IMO, but we're not at all tied to Emby releases anymore this being a hard fork, so I don't see much purpose in referencing Emby API versions in our version. We can keep the backend "API version" separate, since that will remain `3.5.2.X` for as long as we need. `4.0` seems arbitrary as well, as it's just one above Emby's versioning, and if they do eventually release a 4.0 (which is likely to be on their future roadmap) that will cause even more confusion. 10 is such a clear difference that there will never reasonably be a conflict, it's a nice round number, and makes it very clear we've forked and are moving on.

**Comment by balasankarc** [comment]
> 10.X.Y, with X being major feature releases and Y being bugfixes

I assume this is following SemVer and 10 will be bumped to 11 when backward incompatible changes are made to APIs. Am I right?

**Comment by joshuaboniface** [comment]
@balasankarc Yup!
