### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#3204]
## Linux (once finalized, propagate to each OS)
- [ ] Verify plugins (break apart to each plugin)
- [ ] playlists
- [ ] Verify fresh install and adding libraries of specific sizes with history of benchmarks for each major release
- [ ] Update from previous major release and libraries
    - [ ] Use data from very old installs for ef core migrations (ideally pre-fork. this is to confirm we still allow users to skip versions. retain this checkbox until we settle on dropping) the migrations from the old schema
- [ ] user creation and deletion and modifcation
    - [ ] admin settings
    - [ ] user display settings
    - [ ] user settings

## Generic
- [ ] Verify all builds
- [ ] Clients
- [ ] Base URL: DLNA, Chromecast, VLC
- [ ] chromecast
- [ ] external clients (sonarr etc)
- [ ] dlna
- [ ] Verify Live TV on each client (break apart, with and without transcoding, also break apart specific test channels with different aspect ratios 4:3, 16:9)
- [ ] HDHr

### Clients
- [ ] Verify resume function and proper saving
- [ ] subtitles (each type, internal/external, non-roman)
- [ ] During playback, rapidly skip ahead/skip back to verify behavior (especially during subs)
- [ ] Firefox
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] Firefox ESR/Mobile
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] Chrome
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] Chrome Mobile
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] Safari
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] Safari Mobile
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] Android
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
    - [ ] ExoPlayer
- [ ] Android TV
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
    - [ ] login page with public user, verify last login time displays for existing user that has logged in
    - [ ] login page with public user, verify last login time doesnt cause problem for existing user that has NOT logged in
    - [ ] ExoPlayer
    - [ ] External Player
    - [ ] Client options and Change server buttons in settings
- [ ] Fire Stick
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
    - [ ] login page with public user, verify last login time displays for existing user that has logged in
    - [ ] login page with public user, verify last login time doesnt cause problem for existing user that has NOT logged in
    - [ ] ExoPlayer
    - [ ] External Player
    - [ ] Client options and Change server buttons in settings
- [ ] iOS
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] Kodi
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] Tizen
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images
- [ ] UWP
    - [ ] login page with/without/mixed public users
    - [ ] login page with/without/mixed public users with profile images

## Codec Support

# Video
| Codec   | Web                                         | Android TV                               | Firestick TV | Android | iOS | Kodi |
| :--------- | :--------------------------------------: | :--------------------------------------: | :---------------: | :--------: | :-: | :-: |
| H264 8bit 16:9 | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| H264 8bit 4:3 | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| H264 8bit anamorphic    | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| H264 10bit | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| H265 8bit SDR | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| H265 10bit SDR | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| HDR10 | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| HDR10+ | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| DV | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| HLG | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| VP8 | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| VP9 | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |

# Audio
| Codec   | Web                                         | Android TV                               | Firestick TV | Android | iOS | Kodi |
| :--------- | :--------------------------------------: | :--------------------------------------: | :---------------: | :--------: | :-: | :-: |
| MP3      | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| AAC      | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| EAC3    | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| AC3      | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| OPUS   | <ul><li>- [ ] Firefox</li><li>- [ ] Firefox ESR/Mobile</li><li>- [ ] Chrome</li><li>- [ ] Chrome Mobile</li><li>- [ ] Safari</li><li>- [ ] Safari Mobile</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Internal Player</li><li>- [ ] External Player</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |

# Subtitles
| Codec      | Internal                                   |                                    External |
| :------------ | :-------------------------------------: | :--------------------------------------: |
| SRT         | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| SSA         | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| ASS         | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| TTML       | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| EIA-608   | <ul><li>- [ ] Working</li></ul> | |
| DVDSUB | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |
| PGSSUB | <ul><li>- [ ] Working</li></ul> | <ul><li>- [ ] Working</li></ul> |

**Comment by Bond-009** [comment]
FreeBSD support isn't here yet ;)

**Comment by Artiume** [comment]
@mcarlton is still slacking, that's all

**Comment by joshuaboniface** [comment]
I like this and it's ambitious, but do we have a reasonable way to test all of this stuff? A big issue for me personally is a very limited test set without tons of manual work to set up a dozen different instances. Are we going to distribute this amongst contributors, automate it, etc.?

**Comment by Artiume** [comment]
Ideally it becomes the norm as a quick check and people just use it to see what's been checked so far and what needs to be checked if there's been specific known issues in areas. I think if you try and get 100% completion everytime, it'd be counter productive.

As for automation, that would be ideal but that's not my wheel house.

**Comment by Artiume** [comment]
we'll eventually use this, i swear

**Comment by PrplHaz4** [comment]
> 
> 
> we'll eventually use this, i swear

just in time for the official RC 🤣

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/issues/4520 10.7 checklist
