### ISSUE TITLE
[Meta] List to track user customizable theme support

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#370]
Just a "master" list to track known issues working towards user supplied themes.

* [ ]  Make it so themes are not hard coded #367
* [ ] Move all theme related color codes to theme .css files #368
* [ ] Add way to upload user themes #369

**Comment by sparky8251** [comment]
If you want. So far I've just been making these meta issues to track similar tasks. No sense having 200 issues with no organization, right?

Can also project up the other one I opened.

**Comment by anthonylavado** [comment]
@sparky8251 Move this over to -web?
