### ISSUE TITLE
Convert strings to enums

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin#4214]
A lot of our API uses strings to communicate where enums would be preferable. Converting those properties to enums will help the apiclient generation and automatically documents all valid values, causing less errors introduced via misspelling or wrong capitalization.

For example: the image API contains a parameter called "format". I know the value can be "png". But can it also be "bmp"? You won't know if the server just says it's a string, an enum will always make sure all available options are exposed and no more or less.

## Missing types
_Feel free to leave a comment (or edit this post directly) to add types not listed_

**File name** - **Property** - **Pull Request**

### Api
- [x] Jellyfin.Api/Controllers/ImageController - GetItemImage.format - #4259
- [x] Jellyfin.Api/Controllers/SessionController PostCapabilities.supportedCommands - #4252
- [ ] Jellyfin.Api/Controllers/SubtitleController - GetSubtitle.format

### Common fields

_Most of these are used in multiple controllers_

- [x] Jellyfin.Api/Controllers/* - *.fields - #4302 
- [x] Jellyfin.Api/Controllers/* - *.filters - #4303 
- [ ] Jellyfin.Api/Controllers/* - *.sortBy
- [x] Jellyfin.Api/Controllers/* - *.sortOrder - #5091
- [ ] Jellyfin.Api/Controllers/* - *.excludeItemTypes
- [x] Jellyfin.Api/Controllers/* - *.excludeLocationTypes - #4304 
- [ ] Jellyfin.Api/Controllers/* - *.includeItemTypes
- [x] Jellyfin.Api/Controllers/* - *.imageTypes - #4305 
- [x] Jellyfin.Api/Controllers/* - *.enableImageTypes - #4305 
- [ ] Jellyfin.Api/Controllers/* - *.mediaTypes
- [ ] Jellyfin.Api/Controllers/* - *.personTypes
- [ ] Jellyfin.Api/Controllers/* - *.libraryContentType
- [ ] Jellyfin.Api/Controllers/* - *.collectionType

### Models

- [ ] MediaBrowser/Model/Session/ClientCapabilities - PlayableMediaTypes
- [x] MediaBrowser/Model/Session/ClientCapabilities - SupportedCommands
- [ ] MediaBrowser/Model/Dto/BaseItemDto - Type

### WebSockets

- [x] MediaBrowser.Model/Session/GeneralCommand - Name - #4192
- [x] MediaBrowser.Model/Net/WebSocketMessage - MessageType - #4210

## Helping out

Want to help fix these issues? Awesome! Please leave a comment which type you're working on (and check if no-one else it working on it already) and link to this issue when creating your pull request.

For questions about the code or discussing something else our [Matrix channels](https://jellyfin.org/docs/general/getting-help.html) are open 24/7!

**Comment by skyfrk** [comment]
I'll take on `Jellyfin.Api/Controllers/SessionController PostCapabilities.supportedCommands` and `MediaBrowser/Model/Session/ClientCapabilities - SupportedCommands` in one PR.

**Comment by ConfusedPolarBear** [comment]
I can convert `Jellyfin.Api/Controllers/ImageController - GetItemImage.format`.

**Comment by crobibero** [comment]
Notes: `sortBy`, `orderBy` can't be easily converted 

`includeItemTypes`, `excludeItemTypes` need to stay as string because they're used in the `InternalItemsQuery` mess.

**Comment by nielsvanvelzen** [comment]
It's unfortunate we can't convert those right now. Do you think it's possible when the database migration is done?

**Comment by crobibero** [comment]
Yep, they can all be changed once database migration is done, or if we were to change  how the query is generated (boooooo)

**Comment by crobibero** [comment]
Todo- change all enum to be not-plural

**Comment by nielsvanvelzen** [comment]
Closing this issue now as it became slightly outdated, most (but not all 😉) properties use enums now!
