### ISSUE TITLE
[Meta] List of Metadata Manager enhancements

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#504]
* [ ] Request: better metadata manager #502
* [ ] Add "Comments" field #246
* [ ] Editing Metadata for multiple items at once jellyfin/jellyfin-web#105

**Comment by mysther78** [comment]
Hello, since I've been using Jellyfin, the comments feature is really the one I'm looking forward to more.
I'm not sure if this post belongs here but it will allow me to have notifications if there are changes on this post!

**Comment by srcrist** [comment]
Closing this issue as it does not contain an actual Jellyfin bug. It appears that all of the tracked feature proposals have already been migrated to fider.
